---

platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ykisialiou/terraform-docker
    tag: 0.11.14 

params: {}

inputs:
  - name: platform-automation
  - name: platform-automation-config
  - name: terraforming-aws

outputs:
  - name: generated-state 

run:
  path: platform-automation/tasks/terraform-aws/task.sh

